package main

import (
	"bufio"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"text/template"

	"github.com/gertd/go-pluralize"
	"github.com/schollz/progressbar/v3"
)

var (
	dictionaryFile       string
	commonDictionaryFile string
	profanityFile        string
	blacklistFile        string
	falsePositiveFile    string
	goFilename           string

	plural = pluralize.NewClient()
)

const goTemplateSrc = `package moderation

// Code generated by generator/filter_dictionary.go; DO NOT EDIT

// seeing word [key] means changing inappropriate level by [value]
var wordValues = {{.WordValues}}
`

func init() {
	if len(os.Args) != 7 {
		log.Fatalf("expected 7 args, got %d", len(os.Args))
	}
	dictionaryFile = os.Args[1]
	commonDictionaryFile = os.Args[2]
	profanityFile = os.Args[3]
	blacklistFile = os.Args[4]
	falsePositiveFile = os.Args[5]
	goFilename = os.Args[6]
}

func fileToStrings(filename string) (lines []string) {
	buf, err := ioutil.ReadFile(filename)
	if err != nil {
		log.Fatal(err)
	}
	str := string(buf)
	reader := strings.NewReader(str)
	scanner := bufio.NewScanner(reader)
	for scanner.Scan() {
		lines = append(lines, scanner.Text())
	}
	return
}

// each line contains [key],[value]
func fileToStringValues(filename string) (values map[string]int) {
	values = make(map[string]int)

	buf, err := ioutil.ReadFile(filename)
	if err != nil {
		log.Fatal(err)
	}
	str := string(buf)
	reader := strings.NewReader(str)
	scanner := bufio.NewScanner(reader)
	for scanner.Scan() {
		line := scanner.Text()
		lineSegments := strings.Split(line, ",")
		key := lineSegments[0]
		value, _ := strconv.Atoi(lineSegments[1])
		values[key] = value
	}
	return
}

func main() {
	dictionary := fileToStrings(dictionaryFile)
	commonDictionary := fileToStrings(commonDictionaryFile)
	profanities := fileToStringValues(profanityFile)
	blacklistRaw := fileToStrings(blacklistFile)
	falsePositives := fileToStrings(falsePositiveFile)

	for _, falsePositive := range falsePositives {
		dictionary = append(dictionary, falsePositive)
	}

	var blacklistRegexes []*regexp.Regexp
	for _, raw := range blacklistRaw {
		r := regexp.MustCompile(raw)
		blacklistRegexes = append(blacklistRegexes, r)
	}

	filtered := make(map[string]int)

	var combinationWords []string

	shortValid := map[string]bool{
		"all":  true,
		"also": true,
		"and":  true,
		"any":  true,
		"are":  true,
		"as":   true,
		"back": true,
		"be":   true,
		"but":  true,
		"by":   true,
		"can":  true,
		"come": true,
		"day":  true,
		"do":   true,
		"for":  true,
		"from": true,
		"have": true,
		"he":   true,
		"her":  true,
		"his":  true,
		"how":  true,
		"give": true,
		"go":   true,
		"good": true,
		"one":  true,
		"it":   true,
		"my":   true,
		"not":  true,
		"she":  true,
		"the":  true,
		"to":   true,
		"with": true,
		"you":  true,
	}

search:
	for _, word := range commonDictionary {
		if len(word) < 3 && !shortValid[word] {
			continue
		}

		wordSingular := plural.Singular(word)

		for profanity := range profanities {
			if word == profanity || wordSingular == profanity {
				continue search
			}
		}

		for _, r := range blacklistRegexes {
			if RegexMatchAll(r, word) {
				continue search
			}
		}

		combinationWords = append(combinationWords, word)
	}

	fmt.Printf("Dictionary has %d words\n", len(dictionary))
	fmt.Println()
	fmt.Println("Testing word combinations...")
	bar := progressbar.New(len(combinationWords))

	//endOfNormalDictionary := len(dictionary) - 1

	for _, word1 := range combinationWords {
		bar.Add(1)
		for _, word2 := range combinationWords {
			combined := word1 + word2
			for profanity := range profanities {
				// These profanities create too many false positives
				// (this check must be in sync with the moderation runtime)
				if len(profanity) <= 3 || (len(profanity) <= 4 && profanity[0] == 's') {
					continue
				}
				idx := strings.Index(combined, profanity)
				if idx != -1 && idx > len(word1)-len(profanity) && idx < len(word1) {
					dictionary = append(dictionary, combined)
					break
					//println(word1, word2)
				}
			}
		}
	}

	fmt.Println()
	fmt.Printf("Dictionary now has %d words\n", len(dictionary))
	fmt.Println()
	fmt.Println("Filtering dictionary...")
	bar = progressbar.New(len(dictionary))

filtering:
	for _, word := range dictionary {
		bar.Add(1)

		wordSingular := plural.Singular(word)

		falsePositiveValue := 0

		for profanity, value := range profanities {
			if word == profanity || wordSingular == profanity {
				// is a profane word, so is not false positive
				continue filtering
			}
			if strings.Index(word, profanity) != -1 {
				falsePositiveValue -= value
			}
		}

		if falsePositiveValue == 0 {
			// does not contain any profane words, so is irrelevant
			continue filtering
		}

		for _, r := range blacklistRegexes {
			if RegexMatchAll(r, word) {
				// is a blacklisted word, so is not false positive
				continue filtering
			}
		}

		filtered[word] = falsePositiveValue
	}

	fmt.Println()
	fmt.Printf("Dictionary now has %d words\n", len(filtered))
	fmt.Println()
	fmt.Println("Removing redundancies...")

	// sort by length to find and remove redundancies in the right order
	sortedFilteredKeys := make([]string, 0, len(filtered))

	for word := range filtered {
		sortedFilteredKeys = append(sortedFilteredKeys, word)
	}

	sort.Slice(sortedFilteredKeys, func(i, j int) bool {
		return len(sortedFilteredKeys[i]) < len(sortedFilteredKeys[j])
	})

	bar = progressbar.New(len(filtered))

outer:
	for _, word1 := range sortedFilteredKeys {
		bar.Add(1)

		count1 := filtered[word1]

		// word1 is the long word that may be redundant
		// word2 is the short word that may make word1 redundant

		//var testing = make(map[string]int)

		for word2, count2 := range filtered {
			if len(word1) > len(word2) && strings.Index(word1, word2) != -1 {
				count1 -= count2
				//testing[word2]=count2

				if count1 >= 0 {
					if count1 > 0 {
						// for debugging
						//fmt.Printf("\nwarning: false positive '%s' (originally %d) achieved positive value %d (%v)\n", word1, filtered[word1], count1, testing)
					}
					delete(filtered, word1)
					continue outer
				}
			}
		}

		filtered[word1] = count1
	}

	bar.Finish()

	// add profanity
	for profanity, value := range profanities {
		filtered[profanity] = value
	}

	longest := 0

	for word := range filtered {
		if len(word) > longest {
			longest = len(word)
		}
	}

	fmt.Println()
	fmt.Printf("Dictionary now has %d words, the longest having %d letters\n", len(filtered), longest)
	fmt.Println()

	fmt.Println("Writing output file...")

	goFile, err := os.Create(goFilename)
	if err != nil {
		log.Fatal(err)
	}
	goTemplate, err := template.New("go").Parse(goTemplateSrc)
	if err != nil {
		panic(err)
	}
	err = goTemplate.Execute(goFile, map[string]interface{}{
		"WordValues": fmtMap(filtered),
	})
	if err != nil {
		log.Fatal(err)
	}
	err = goFile.Close()
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println("Done.")
}

func fmtSlice(slice []string) string {
	var builder strings.Builder
	builder.WriteString("[]string{\n")
	for _, str := range slice {
		builder.WriteString(fmt.Sprintf("	\"%s\",\n", str))
	}
	builder.WriteString("}")
	return builder.String()
}

func fmtMap(m map[string]int) string {
	// store in slice for sorting keys
	slice := make([]string, 0, len(m))

	for word := range m {
		slice = append(slice, word)
	}

	sort.Strings(slice)

	var builder strings.Builder
	builder.WriteString("map[string]int8{\n")
	for _, word := range slice {
		builder.WriteString(fmt.Sprintf("	\"%s\": %d,\n", word, int8(m[word])))
	}
	builder.WriteString("}")
	return builder.String()
}

func RegexMatchAll(pattern *regexp.Regexp, str string) bool {
	pattern.Longest()
	return len(pattern.FindString(str)) == len(str)
}
